#!/usr/bin/env bash

echo "|> prepare env"
export CWD=$(pwd)
export REVISION=$(git rev-parse --short HEAD)
source ~/.gimme/envs/gotip.env

echo "|> build gateway-http"
docker \
	-e GODEBUG=netdns=go \ # Force go resolver as our container doesn't ship the dependency.
	--rm \
	-v ~/.go_workspace:/go
	-w /go/src/github.com/tapglue/snaas \
	golang:1.7.3-alpine \
	go build \
		-ldflags "-X main.revision=${REVISION}" \
		-o gateway-http_${CIRCLE_BUILD_NUM} \
		cmd/gateway-http/*.go

echo "|> build sims"
docker \
	-e GODEBUG=netdns=go \ # Force go resolver as our container doesn't ship the dependency.
	--rm \
	-v ~/.go_workspace:/go
	-w /go/src/github.com/tapglue/snaas \
	golang:1.7.3-alpine \
	go build \
		-ldflags "-X main.revision=${REVISION}" \
		-o sims_${CIRCLE_BUILD_NUM} \
		cmd/sims/*.go

echo "|> build container"
docker build \
	-f ${CWD}/infrastructure/docker/snaas.docker \
    -t tapglue/snaas:${CIRCLE_BUILD_NUM} \
    --build-arg GATEWAY_HTTP_BINARY=gateway-http_${CIRCLE_BUILD_NUM} \
    --build-arg SIMS_BINARY=sims_${CIRCLE_BUILD_NUM} \
    ${CWD}